image: node:9.6.1

pipelines:
  default:
    - step:
        name: Test
        script:
          - yarn install
          - yarn test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
