export const ACTION = {
  PLAYLISTS_LOAD_BEGIN: 'PLAYLISTS_LOAD_BEGIN',
  PLAYLISTS_LOAD_SUCCESSFUL: 'PLAYLISTS_LOAD_SUCCESSFUL',
  PLAYLISTS_LOAD_ERROR: 'PLAYLISTS_LOAD_ERROR',
  PLAYLISTS_SAVE: 'PLAYLISTS_SAVE',
  PLAYLISTS_SELECT: 'PLAYLISTS_SELECT',
  SAVE_TRACKS: 'SAVE_TRACKS',
};

export const LOADING = {
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};
