export const ACTION = {
  SET_PLAYLISTS_LOADING_STATUS: 'SET_PLAYLISTS_LOADING_STATUS',
  PLAYLISTS_SAVE: 'PLAYLISTS_SAVE',
  PLAYLISTS_SELECT: 'PLAYLISTS_SELECT',
  SAVE_TRACKS: 'SAVE_TRACKS',
};

export const LOADING = {
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};
